---
title: "R Notebook"
output: html_notebook
---


```{r}
library(matlib)
library(ISLR)
library(lsr)
#exercise 3
#1.1
f <- function(x) {
  result <- x^3 + x^2 -6
  return(result)
}
f
```

```{r}
#1.2
g <- function(a,b) {
  gx <- a%*%b%*%(b-a)
  return(gx)
}
g



```
```{r}
#1.3
#h(m, n) = (√m/n) + m − 2n
h <- function(m, n) {
  hx <- (sqrt(m)/n) + m - 2*n
  return(hx)
}
h


```


```{r}
#2.1

a <- matrix(c(5:8),2,2,TRUE)
b <- matrix(c(9:12),2,2,TRUE)
a
b

#f(a, b) = (a + b)ab
f <- function(a, b) {
  fab <- (a+b)%*%a%*%b
  return(fab)
}
f

```



```{r}
#2.2
#MATRIX
m <- matrix(c(3:6),2,2,TRUE)
n <- matrix(c(2:5),2,2,TRUE)
m
n

```
```{r}
#h(m, n) = |m|n − mn
h <- function(m,n){
  mn <- det(m)*n - m%*%n
  return(mn)
}
h

```
```{r}
#2.3
#g(x) = x'x − 2x
#matrixnya
x <- matrix(c(4:7),2,2,TRUE)
y <- t(x) #transpos dari x

x
y
```



```{r}
g <- function(x) {
  gx <- t(x)-2*x
  return(gx)
}
g

```

```{r}
#exercise 4 
#f(x) = sin(x)
f <- function(x) {
  fx <- x*sin(x)
  return(fx)
  }

f

#grafiknya
input <- 0:10
plot(input,
sapply(input, f), type = "l" , xlab = "x" , ylab = " plot f(x)" )


```

```{r}
#f(x) = log(x)
f <- function(x) {
  fx <- log(x)
  return(fx)
}
f

input <- 0:10
plot(input,
sapply(input, f), type = "l" , xlab = "x" , ylab = "plot log(x)" )

```

```{r}
#√x − 2
f <- function(x) {
  fx <- sqrt(x)-2
  return(fx)
}
f

input <- 0:10
plot(input,
sapply(input, f), type = "l" , xlab = "x" , ylab = "plot akar f(x)" )

```

```{r}
#√(x − 2)
f <- function(x) {
  fx <- sqrt(x-2)
  return(fx)
}
f


input <- 0:10
plot(input,
sapply(input, f), type = "l" , xlab = "x" , ylab = "plot akar f(x) = x-2" )
```


```{r}
#√(2 − x)
f <- function(x) {
  fx <- sqrt(2-x)
  return(fx)
}
f


input <- 0:10
plot(input,
sapply(input, f), type = "l" , xlab = "x" , ylab = "plot akar f(x) = (2-x)" )
```


```{r}
#exercise 4 cont'd
#a 
y <- function(x){
  yx <- x^3
  return(yx)
}
y

```

```{r}
#b 
#x^3 -2*x^2 - 3*x + 4
y <- function(x){
  yx <- (x^3) - 2*x^2 -3*x + 4
  return(yx)
}
y


```

```{r}
#c= 2x^3 - x + 5
y <- function(x){
  yc <- 2*x^3- x + 5
  return(yc)
}
y


```

```{r}
#d x^3  - 3*x^2 + 3*x - 1
y <- function(x){
  yd <- x^3- 3*x^2 + 3*x- 1
  return(yd)
}
y

```


```{r}
#e 
y <- function(x){
  ye <--x^3
  return(ye)
}
y

```


```{r}
#f 
#-x^3 +2*x^2 + 3*x - 4
y <- function(x){
  yf <-(-x)^3 + 2*x^2 + 3*x- 4
  return(yf)
}
y

```


```{r}
#g
#x^4
y <- function(x){
  yg <- x^4
  return(yg)
}
y


```


```{r}
#h
#x^4 - x^3 - x^2 + x + 1
y <- function(x){
  yh <-x^4- x^3- x^2 + x + 1
  return(yh)
}
y


```


```{r}
#i
#x^4 - 3*x^3 + 2*x^2 + x - 1
y <- function(x){
  yi <-x^4- 3*x^3 + 2*x^2 + x- 1
  return(yi)
}
y


```


```{r}
#j
#x^4 - 4*x^3 + 6*x^2 - 4*x
y <- function(x){
  yj <- x^4 - 4*x^3 + 6*x^2 - 4*x
  return(yj)
}
y

```


```{r}
#k
#-x^4
y <- function(x){
  yk <--x^4
  return(yk)
}
y

```

```{r}
#l
#-x^4 - 2*x^3 + 3*x
y <- function(x){
  yl <- -x^4 - 2*x^3 + 3*x
  return(yl)
}
y

```

